<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\Data;

$admins = Data::get("admins");
//var_dump($users);

Layout::includeLayout('adminheader');

?>
    <!-- container -->
    <div class="container" style="padding-top: 60px;width:100%;padding-left: 50px;height:75vh;">
    <h1 style="color:white;text-align:center;">Admins</h1>
        <form class="" method="POST" role="form" action="<?=Url::toRoute('admin/block')?>">
            <table class="table table-fixed" style="width:50%;background-color: #f3f3f3; margin: 0px auto;margin-bottom: 100px;">
                <thead>
                    <tr>
                        <th class="col-xs-1">ID</th>
                        <th class="col-xs-3">Username</th>
                        <th class="col-xs-4">Email</th>
                        <th class="col-xs-1" style="text-align: right;">Block</th>
                    </tr>
                </thead>
                <tbody style="height:200px;overflow-y:auto;width: 100%;">
                <?php foreach($admins as $admin){ ?>
                    <tr>
                        <td name="id" class="col-xs-1"><?=$admin->id?></td>
                        <td class="col-xs-3"><?=$admin->username?></td>
                        <td class="col-xs-4"><?=$admin->email?></td>
                        <td class="col-xs-1" style="text-align: right;">
                            <?php if($admin->block == 0){ ?>
                                <button type="submit" class="btn btn-warning btn-block" name="block" value="<?=$admin->id?>">Block</button>
                                <!--<input type="submit" class="btn btn-warning btn-block" name="block" value="Block"> -->
                            <?php }else{ ?>
                                <button type="submit" class="btn btn-success btn-block" name="unblock" value="<?=$admin->id?>">UnBlock</button>
                                <!--<input type="submit" class="btn btn-success btn-block" name="unblock" value="UnBlock"> -->
                            <?php } ?>
                        </td>
                    </tr>
                <?php } ?>
                    
                </tbody>
            </table>
        </form>
    </div>	<!-- /container -->

<?php Layout::includeLayout('footer')?>