<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\Data;

$user = Data::get("user");

$erroNewPass = Data::get("erroNewPass");
$erroRepeatPass = Data::get("erroRepeatPass");
$erroLenghtPass = Data::get("erroLenghtPass");
$erroPassNotTheSame = Data::get("erroPassNotTheSame");
$erroPassSameAsOld = Data::get("erroPassSameAsOld");
$passwordChanged = Data::get("passwordChanged");

Layout::includeLayout('adminheader');

?>
    <!-- container -->
    <div class="container" style="padding-top: 70px;width:100%;padding-left: 50px;height:75vh;">
        <div class="" style="width: 45%;margin: 0 auto; text-align: center;">
            <h1 style="color:white;text-align:center;">Change password of the admin: <?=$user->username?></h1>
            <?php if($passwordChanged->errors != null){?>
                    <h5 style="color:white;" ><?= $passwordChanged->errors ?></h5>
                    <form class="" method="POST" role="form" action="<?=Url::toRoute('admin/users');?>">
                        <div class="form-group">
                            <div class="col-sm-9 col-sm-offset-3">
                                <input type="submit" class="btn btn-primary btn-block" value="Redirect to the users block">
                            </div>
                        </div>
                    </form>
            <?php }else{ ?>
                <form class="" method="POST" role="form" action="<?=Url::toRoute('admin/changePassword')?>">
                    <?php if($erroNewPass->errors != null){?>
                        <h5 style="color:white;" ><?= $erroNewPass->errors ?></h5>
                    <?php } ?> 
                    <?php if($erroPassNotTheSame->errors != null){?>
                        <h5 style="color:white;" ><?= $erroPassNotTheSame->errors ?></h5>
                    <?php } ?> 
                    <?php if($erroPassSameAsOld->errors != null){?>
                        <h5 style="color:white;" ><?= $erroPassSameAsOld->errors ?></h5>
                    <?php } ?>
                    <?php if($erroLenghtPass->errors != null){?>
                        <h5 style="color:white;" ><?= $erroLenghtPass->errors ?></h5>
                    <?php } ?> 
                    <div class="form-group">
                        <label for="password" class="col-sm-3 control-label">New Password</label>
                        <div class="col-sm-9">
                            <input type="password" name="newPass" maxlength="30" placeholder="Password" class="form-control">
                        </div>
                    </div>
                    <?php if($erroRepeatPass->errors != null){?>
                        <h5 style="color:white;" ><?= $erroRepeatPass->errors ?></h5>
                    <?php } ?> 
                    <div class="form-group">
                        <label for="password" class="col-sm-3 control-label">Repeat the Password</label>
                        <div class="col-sm-9">
                            <input type="password" name="repeatPass" maxlength="30" placeholder="Password" class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-9 col-sm-offset-3">
                            <input type="submit" class="btn btn-primary btn-block" value="Change Password">
                        </div>
                    </div>
                </form>
            <?php } ?>
        </div>
    </div>	<!-- /container -->

<?php Layout::includeLayout('footer')?>