<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\Data;

$erroUsername = Data::get('erroUsername');
$erroPass = Data::get('erroPass');

Layout::includeLayout('adminheader');

?>
    <!-- container -->
    <div class="container" style="padding-top: 60px;width:100%;padding-left: 50px;height:75vh;">

        <div class="" style="width: 35%;margin: 0 auto; text-align: center;">
                <form class="form-horizontal" method="POST" role="form" action="<?=Url::toRoute('admin/login')?>">
                    <h2 style="color:white;" >Admin Login</h2>
                    <?php if($erroUsername->errors != null){?>
                        <h5 style="color:white;" ><?= $erroUsername->errors ?></h5>
                    <?php } ?>           
                    <div class="form-group">
                        <label for="firstName" class="col-sm-3 control-label">username</label>
                        <div class="col-sm-9">
                            <input type="text" value="<?php if($erroPass->errors != null){ echo $erroPass->username;} ?>" name="username" placeholder="username" class="form-control" autofocus>
                        </div>
                    </div>
                    <?php if($erroPass->errors != null){?>
                        <h5 style="color:white;" ><?= $erroPass->errors ?></h5>
                    <?php } ?>
                    <div class="form-group">
                        <label for="password" class="col-sm-3 control-label">Password</label>
                        <div class="col-sm-9">
                            <input type="password" name="pass" placeholder="Password" class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-9 col-sm-offset-3">
                            <input type="submit" class="btn btn-primary btn-block" value="Login">
                        </div>
                    </div>
                </form>  
            </div>

    </div>	<!-- /container -->

<?php Layout::includeLayout('footer')?>