<footer id="footer" class="top-space">

<div class="footer2">
    <div class="container">
        <div class="row">
            <div class="widget-body">
                <p class="text-center">
                    Copyright &copy; 2017/2018, Francisco Melícias, Dárcio Silva, Gustavo Santos
                </p>
                <p class="text-right">
                    Site template by Sergey Pozhilov.
                </p>
            </div>
        </div> <!-- /row of widgets -->
    </div>
</div>

</footer>

<!-- JavaScript libs are placed at the end of the document so the pages load faster -->

<?php
use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\Facades\DebugRenderer;
?>

<?=AssetBundler::js()?>

<script>hljs.initHighlightingOnLoad();</script>

</body>
</html>