<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\WebObjects\URL;
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport"    content="width=device-width, initial-scale=1.0">
    <meta name="author"      content="Francisco Melicias">

    <title>BlackJack</title>

    <?=AssetBundler::css()?>

    <link rel="shortcut icon" href="<?= Asset::image('blackjack_small_icon.png')?>">
    <link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <!-- Custom styles for our site template -->
    <link rel="stylesheet" href="<?= Asset::css('/bootstrap-theme.css')?>" media="screen" >

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="<?= Asset::js('html5shiv.js')?>"></script>
    <script src="<?= Asset::js('respond.min.js')?>"></script>
    <![endif]-->
</head>

<body class="home">
<!-- Fixed navbar -->
<div class="navbar navbar-inverse navbar-fixed-top headroom" >
    <div class="container">
        <div class="navbar-header">
            <!-- Button for smallest screens -->
            <a class="navbar-brand" href="<?= URL::toRoute('base/index')?>"><img src="<?= Asset::image('blackjack_small_icon.png')?>" alt="BlackJack" width="50" height="50"></a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav pull-right">
                <li class="active"><a href="<?= URL::toRoute('base/index')?>">Página inicial</a></li>
                <li><a href="<?= URL::toRoute('base/index')?>">JackPot</a></li>
                <li><a class="btn" href="<?= URL::toRoute('base/index')?>">Registar / Login</a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div>
<!-- /.navbar -->
<header id="head" class="secondary"></header>