<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;
if(Session::has('userid')){
    Layout::includeLayout('header');
}else{
    Layout::includeLayout('headerindex');
}?>

    <!-- Header -->
    <header id="head">
        <div class="container">
            
        </div>
    </header>
    <!-- /Header -->

    <!-- container -->
    <div class="container">

        

    </div>	<!-- /container -->

<?php Layout::includeLayout('footer')?>