<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\Data;

$jackpots = Data::get("jackpots");

if(Session::has('userid')){
    Layout::includeLayout('header');
}else{
    Layout::includeLayout('headerindex');
}?>

    <!-- Header -->
        <div class="container"style="width:100%;height:100%;background: #181015;" >
            <div style="margin: auto;width: 50%; padding: 100px;color:white;">
            <table class="table">
                <thead class="thead">
                    <tr>
                        <th scope="col">Username</th>
                        <th scope="col">Credits won</th>
                        <th scope="col">Date</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach($jackpots as $jackpot){?>
                    <tr>
                    <td><?=$jackpot->username?></td>
                    <td><?=$jackpot->value_won?></td>
                    <td><?=$jackpot->bj_date->format('Y-m-d')?></td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
            </div>
        </div>
    <!-- /Header -->
<?php Layout::includeLayout('footer')?>