<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\Data;

    $userMovements = Data::get('userMovements');
    $user = Data::get("user");

Layout::includeLayout('header');?>

    <!-- Header -->
        <div class="container"style="width:100%;height:100%;background: #181015;" >
            <div>
                <form class="" method="POST" role="form" action="<?=Url::toRoute('money/addFunds')?>">
                    <div class="" style ="width: 200px;margin: 0 auto;margin-top: 70px;padding-bottom: 15px;">
                        <input style="float:left;margin-bottom: 5px;" type="number" name="funds" min="1" max="10000" placeholder="Money to add in €" class="form-control">
                        <input type="submit" class="btn btn-primary btn-block" value="Add funds">
                        <p style='text-align:center;color:white;'>1€ = 4 credits</p>
                </form>
            </div>
            <h4 style='text-align:center;color:white;'> Current credits:  <?=$user->money?> </h4>
            <table class="table table-bordered" style="background:white;">
                <thead>
                    <tr>
                        <th>Data/Hora</th>
                        <th>Tipo</th>
                        <th>Descrição</th>
                        <th>Crédito</th>
                        <th>Débito</th>
                        <th>Saldo</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                    <?php foreach($userMovements as $userMovement){ ?>
                        <td><?=$userMovement->movement_date->format('Y-m-d H:i:s') ?></td>
                        <td><?=$userMovement->money_type ?></td>
                        <td><?=$userMovement->description ?></td>
                        <td><?php if($userMovement->credito != null){echo $userMovement->credito;} ?></td>
                        <td><?php if($userMovement->debito != null){echo $userMovement->debito;} ?></td>
                        <td><?=$userMovement->saldo ?></td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
            <br><br><br><br>
        </div>

    <!-- /Header -->
<?php Layout::includeLayout('footer')?>
